spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test-code?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: 123456
        hikari:
            poolName: Hikari
            autoCommit: false
            maximum-pool-size: 100
            connection-timeout: 60000
            idle-timeout: 400000
            minimum-idle: 10
            max-lifetime: 480000
            connection-test-query: SELECT 1

    # redis 配置
    redis:
        host: localhost
        password: 123456
        port: 6379
        # 数据库索引
        database: 0
        # 连接超时时间
        timeout: 10s
        lettuce:
            pool:
                # 连接池中的最小空闲连接
                min-idle: 0
                # 连接池中的最大空闲连接
                max-idle: 8
                # 连接池的最大数据库连接数
                max-active: 8
                # #连接池最大阻塞等待时间（使用负值表示没有限制）
                max-wait: -1ms

