# 数据源配置
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        druid:
            url: jdbc:mysql://localhost:3306/test-code?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
            username: root
            password: 123456
            # 初始化，最小，最大连接数
            initialSize: 10
            minidle: 10
            maxActive: 18
            # 获取数据库连接等待的超时时间
            maxWait: 60000
            # 配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
            timeBetweenEvictionRunsMillis: 60000
            #配置测试查询语句
            validationQuery: SELECT 1 FROM dual
            # 配置监控统计拦截的filters,去掉后，监控界面的sql无法统计
            filters: stat,wall
    # redis 配置
    redis:
        host: localhost
        password: 123456
        port: 6379
        # 数据库索引
        database: 0
        # 连接超时时间
        timeout: 10s
        lettuce:
            pool:
                # 连接池中的最小空闲连接
                min-idle: 0
                # 连接池中的最大空闲连接
                max-idle: 8
                # 连接池的最大数据库连接数
                max-active: 8
                # #连接池最大阻塞等待时间（使用负值表示没有限制）
                max-wait: -1ms